### ISSUE TITLE
Add option to see your discarded cards.

### ISSUE THREAD

**Issue by Czompi** [martinkadlec0/hc-tcg#50]
This might not be an issue, but when you use Chest card, but not select a card, you get back your Chest card, so you basically had a way to see your discard pile, that you otherwise cannot do.

**Comment by martinkadlec0** [comment]
I think it is okay for players to see their discarded cards. So the actual issue is that you can't do that without a chest card. I think we can use this ticket to track adding that.

**Comment by RoyaLProg** [comment]
> Scopop#3586 - Okay sorry for the poll thing lol, I think if we even need to have something like that an option to check your deck would be a much better idea, however I don't really think it's necessary since you can't check your deck after the game begins on HC either.
You just have to believe in the heart of the cards

*https://discord.com/channels/1073763159187390584/1073763159933992982/1079226968647667892*

The discord has spoken !

They do not see any reason to have a button to see discarded cards 😢

Should we still add it ? 🤔

**Comment by Scopop** [comment]
Hey y'all! On here because someone in the discord brought this up as it was listed as an issue here. I don't believe it would be that useful to have a constantly viewable discard pile, as the chest card already serves that purpose (and the only current reason to even look in your discard is the chest so that kind of solves itself). While the hermits are able to see their discard pile at any point in time, that isn't used at all and it provides no tactical advantage that I can think of.

As I was typing this Royal posted the link to my message, sorry!

**Comment by martinkadlec0** [comment]
Done.
