### ISSUE TITLE
Zedaph's "Sheep Stare" effect no longer works when Heads is flipped

### ISSUE THREAD

**Issue by MidnightIce25** [martinkadlec0/hc-tcg#67]
This was working yesterday (2 days ago maybe?) but when Heads is flipped, Zedaph's "Sheep Stare" effect is no longer working. The opponent is supposed to attack themselves and they do not. They are still able to attack like normal.

**Comment by martinkadlec0** [comment]
This was changed, previously the opponent would flip two coins at start of their turn and if you got both heads it would reverse the attack.

Now you flip one coin on your attack and if it heads the opponent will flip a second on on their attack and if it heads too the damage is reversed.

This is better because the opponent doesn't know when attacking if the second flip fill be heads or not so he is more likely to risk the attack.
