### ISSUE TITLE
Creating accounts - adding TCG coins - and more !

### ISSUE THREAD

**Issue by RoyaLProg** [martinkadlec0/hc-tcg#70]
Ok hear me out,

Would'nt it be nice to be like in hermitcraft, starting with a starter deck, going into matches and earning coin to buy boosters ?

+ Of course, keep all card deck as now for unofficial matches !

+ Adding account could help to not be impersonnate ( yeah we never know)

+ adding TCG coin is just for this idea to work

+ adding friend list ! (could help for easier invite system)

+ would need a database tho :/

+ still keeping guest system

I could help work on it

**Comment by martinkadlec0** [comment]
Hello, yes this has been suggested multiple times. While I do appreciate help, the issue here is not only the development time (which would be substantial to make all of this work well), but also time needed to review all the changes to the code, making sure it fits the current architecture and maintaining it in the future including the database instances etc.

For now, given our small-ish user base & the option to use discord server to keep in touch with friends etc. I lean towards not going into this direction.
